env:
  - GO111MODULE=on
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod download
brews:
  - github:
      owner: fubarhouse
      name: homebrew-pygmy-go
    folder: dist
    homepage: "https://github.com/fubarhouse/pygmy-go"
    description: "Amazee.io's local development helper tool"
    skip_upload: false
    test: system "#{bin}/pygmy-go version"
    install: bin.install "pygmy-go"
    dependencies:
      - name: go
release:
  github:
    owner: fubarhouse
    name: pygmy-go
  draft: true
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}} {{.Env.USER}}"