---
language: go
go:
  - "1.14.2"

matrix:
  include:

    - name: Testing Framework
      os: linux
      services: docker
      before_install:
        - go mod download
        - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go"));
        - sed -i -e "s|COMMITTAG = \"\"|COMMITTAG = \"${TRAVIS_COMMIT}\"|g" service/library/version.go
        - cat service/library/version.go | grep 'COMMITTAG = "'
        - GO111MODULE=on go vet $(go list ./...);
        - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.25.1 golangci-lint run -v
      script:
        # Build
        - make build
        # Test
        - go test -v

    - name: Linux build w/ tests
      os: linux
      services: docker
      before_install:
        - go mod download
        - diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go"));
        - sed -i -e "s|COMMITTAG = \"\"|COMMITTAG = \"${TRAVIS_COMMIT}\"|g" service/library/version.go
        - cat service/library/version.go | grep 'COMMITTAG = "'
        - GO111MODULE=on go vet $(go list ./...);
        - docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.25.1 golangci-lint run -v
        - wget https://files.devwithlando.io/lando-stable.deb
        - sudo dpkg -i lando-stable.deb
        - lando --experimental
      script:

        # Build
        - go build -o pygmy-go-linux-x86

        # Run pygmy
        - ./pygmy-go-linux-x86 pull;
        - ./pygmy-go-linux-x86 pull;
        - ./pygmy-go-linux-x86 status;
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml up;
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml status;
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml version;

        # Test the amazeeio-network for expected results
        - >
          docker network inspect amazeeio-network | jq '.[].Name' | grep "amazeeio-network";
          docker network inspect amazeeio-network | jq '.[].Containers' | jq '.[].Name' | grep "amazeeio-haproxy";
          docker network inspect amazeeio-network | jq '.[].Containers' | jq '.[].Name' | grep "amazeeio-mailhog";
          docker network inspect amazeeio-network | jq '.[].Containers' | jq '.[].Name' | grep "amazeeio-portainer";
          docker network inspect amazeeio-network | jq '.[].Containers' | jq '.[].IPv4Address';
          docker network inspect amazeeio-network | jq '.[].Containers' | jq '.[].IPv4Address' | grep "10.99.99.";

        # Test for configured container tags.
        - >
          docker inspect amazeeio-dnsmasq   | jq '.[].Config.Labels["pygmy.hocuspocus"]'  | grep "42";
          docker inspect amazeeio-dnsmasq   | jq '.[].Config.Labels["pygmy.abracadabra"]' | grep "1";
          docker inspect amazeeio-dnsmasq   | jq '.[].Config.Labels["pygmy.opensesame"]'  | grep "correct";
        - >
          docker inspect amazeeio-haproxy   | jq '.[].Config.Labels["pygmy.hocuspocus"]'  | grep "42";
          docker inspect amazeeio-haproxy   | jq '.[].Config.Labels["pygmy.abracadabra"]' | grep "1";
          docker inspect amazeeio-haproxy   | jq '.[].Config.Labels["pygmy.opensesame"]'  | grep "correct";
        - >
          docker inspect amazeeio-portainer | jq '.[].Config.Labels["pygmy.hocuspocus"]'  | grep "42";
          docker inspect amazeeio-portainer | jq '.[].Config.Labels["pygmy.abracadabra"]' | grep "1";
          docker inspect amazeeio-portainer | jq '.[].Config.Labels["pygmy.opensesame"]'  | grep "correct";
        - >
          docker inspect amazeeio-ssh-agent | jq '.[].Config.Labels["pygmy.hocuspocus"]'  | grep "42";
          docker inspect amazeeio-ssh-agent | jq '.[].Config.Labels["pygmy.abracadabra"]' | grep "1";
          docker inspect amazeeio-ssh-agent | jq '.[].Config.Labels["pygmy.opensesame"]'  | grep "correct";
        - >
          docker inspect amazeeio-mailhog   | jq '.[].Config.Labels["pygmy.hocuspocus"]'  | grep "42";
          docker inspect amazeeio-mailhog   | jq '.[].Config.Labels["pygmy.abracadabra"]' | grep "1";
          docker inspect amazeeio-mailhog   | jq '.[].Config.Labels["pygmy.opensesame"]'  | grep "correct";

        # Drupal 8 (Drupal Example):
        - git clone https://github.com/amazeeio/drupal-example.git drupal8-lagoon && cd drupal8-lagoon
        - docker-compose -p drupal8-example up -d
        - docker-compose -p drupal8-example exec cli composer install
        - sleep 5
        - curl --HEAD http://drupal-example.docker.amazee.io
        - curl --HEAD http://drupal-example.docker.amazee.io | grep "X-LAGOON"
        - docker-compose -p drupal8-example down
        - docker-compose -p drupal8-example rm
        - cd ../

        # Drupal 8 (Drupal Example Simple):
        - git clone -b 8.x https://github.com/amazeeio/drupal-example-simple.git drupal8-lagoon-simple && cd drupal8-lagoon-simple
        - docker-compose -p drupal8 up -d
        - docker-compose -p drupal8 exec cli composer install
        - sleep 5
        - curl --HEAD http://drupal8-example-simple.docker.amazee.io
        - curl --HEAD http://drupal8-example-simple.docker.amazee.io | grep "X-LAGOON"
        - docker-compose -p drupal8 down
        - docker-compose -p drupal8 rm
        - cd ../

        # Drupal 9 (Drupal Example Simple):
        - git clone -b 9.x https://github.com/amazeeio/drupal-example-simple.git drupal9-lagoon-simple && cd drupal9-lagoon-simple
        - docker-compose -p drupal9 up -d
        - docker-compose -p drupal9 exec cli composer install
        - sleep 5
        - curl --HEAD http://drupal9-example-simple.docker.amazee.io
        - curl --HEAD http://drupal9-example-simple.docker.amazee.io | grep "X-LAGOON"
        - docker-compose -p drupal9 down
        - docker-compose -p drupal9 rm
        - cd ../

        # Drupal 9 (Drupal Example Simple):
        - git clone -b 9.x https://github.com/amazeeio/drupal-example-simple.git drupal9-lagoon-simple-lando && cd drupal9-lagoon-simple-lando
        - lando start
        - curl --HEAD http://drupal9-example-simple-lando.lndo.site:8000
        - curl --HEAD http://drupal9-example-simple-lando.lndo.site:8000 | grep "X-LAGOON"
        - lando destroy -y
        - cd ../

        # Wordpress:
        - git clone https://github.com/amazeeio/wordpress-example.git wordpress && cd wordpress
        - docker-compose -p wordpress up -d
        - docker-compose -p wordpress exec cli composer install
        - sleep 5
        - curl --HEAD http://wordpress-nginx.docker.amazee.io
        - curl --HEAD http://wordpress-nginx.docker.amazee.io | grep "X-LAGOON"
        - docker-compose -p wordpress down
        - docker-compose -p wordpress rm
        - cd ../

        # Node:
        - git clone https://github.com/amazeeio/node-example.git node && cd node
        - npm install
        - docker-compose -p node up -d
        - curl --HEAD http://node.docker.amazee.io
        - curl --HEAD http://node.docker.amazee.io | grep "X-LAGOON"
        - docker-compose -p node down
        - docker-compose -p node rm
        - cd ../

        # Cleanup after tests.
        - docker system prune --all --force

        # Cowsay test
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml down;
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml up | grep '< holy ship >';

        # Cleanup pygmy
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml down;
        - ./pygmy-go-linux-x86 --config examples/pygmy.travis.yml clean;

    - name: Windows build
      os: windows
      services: docker
      before_install:
        - go mod download
        - GO111MODULE=on go vet $(go list ./...);
        - sed -i -e "s|COMMITTAG = \"\"|COMMITTAG = \"${TRAVIS_COMMIT}\"|g" service/library/version.go
        - cat service/library/version.go | grep 'COMMITTAG = "'

      script:
        - export PYGMY_PATH=pygmy-go.exe;

        - go mod vendor
        - rm -f go.mod
        - rm -f go.sum
        - go build -o pygmy-go.exe .
        - cp pygmy-go.exe builds/pygmy-go.exe

        - builds/${PYGMY_PATH} --config examples/pygmy.travis.yml status;
        - builds/${PYGMY_PATH} --config examples/pygmy.travis.yml version;

notifications:
  slack: fubarhouse:upHoIzmKb4ikkBOt2cOwgKXY