name: goreleaser

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        run: sudo apt update && sudo apt install git golang -y
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Establish commit ref for compiled files
        run: sed -i -e "s|COMMITSHA = \"\"|COMMITSHA = \"$GITHUB_SHA\"|g" service/library/version.go
      -
        name: Establish version for compiled files
        run: sed -i -e "s|COMMITTAG = \"\"|COMMITTAG = \"$GITHUB_REF\"|g" service/library/version.go
      -
        name: Echo the version reference
        run: cat service/library/version.go | grep "COMMITTAG =" | grep "refs" | head -n1 | xargs
      -
        name: Echo the commit reference
        run: cat service/library/version.go | grep "COMMITSHA =" | head -n1 | xargs
      -
        name: Fetch Dependencies
        run: go mod download
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --debug --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}