name: goreleaser

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        run: apt update && apt install git -y
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Establish version for compiled files
        run: sed -i -e "s|COMMITTAG = \"\"|COMMITTAG = \"$GITHUB_REF\"|g" service/library/version.go
      -
        run: cat service/library/version.go | grep "COMMITTAG =" | grep -v Getenv
      -
        name: Fetch Dependencies
        run: go mod download
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --debug --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}