name: pygmy

on:
  push:
  pull_request:

jobs:
  pygmy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'
      - name: Install
        run: go mod download
        env:
          GO111MODULE: on
      - name: Diff
        run: diff -u <(echo -n) <(gofmt -d $(find . -not -path "./vendor/*" -name "*.go"));
      - name: Vet
        run: go vet $(go list ./...);
      - name: Lint
        run: docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.25.1 golangci-lint run -v
      - name: Build
        run: make build
      - name: Test
        run: go test -v ./...

  pygmywindows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.14.1'
      - name: Install
        run: go mod download
        env:
          GO111MODULE: on
      - name: Vendor
        run: go mod vendor
      - name: remove mod file
        run: rm go.mod
      - name: remove sum file
        run: rm go.sum
      - name: Build
        run: go build -o pygmy-go.exe .
      - name: Copy the binary
        run: cp pygmy-go.exe builds/pygmy-go.exe
      - name: Run status command
        run: builds/${PYGMY_PATH} --config examples/pygmy.travis.yml status;
      - name: Run version command
        run: builds/${PYGMY_PATH} --config examples/pygmy.travis.yml version;
